# Generated by Django 4.1.3 on 2023-01-12 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificaciones',
            name='fecha',
            field=models.CharField(max_length=30),
        ),
    ]
