# Generated by Django 4.1.3 on 2022-12-07 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ValoresBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_cifra_base', models.IntegerField(max_length=5)),
                ('base', models.IntegerField(max_length=5)),
                ('porcentaje_mora', models.CharField(max_length=5)),
            ],
        ),
    ]
