# Generated by Django 4.1.3 on 2022-12-08 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuraciones', '0002_valoresbase_valor_adicional_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valoresbase',
            name='valor_adicional',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='valoresbase',
            name='valor_cifra_base',
            field=models.DecimalField(decimal_places=2, max_digits=30),
        ),
    ]
