# Generated by Django 4.1.3 on 2022-12-08 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuraciones', '0003_alter_valoresbase_valor_adicional_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valoresbase',
            name='base',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='valoresbase',
            name='porcentaje_mora',
            field=models.IntegerField(),
        ),
    ]
