# Generated by Django 4.1.3 on 2023-01-11 01:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0019_alter_cliente_detalle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cobros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registro', models.DateField()),
                ('fechacifra', models.CharField(max_length=15)),
                ('total', models.IntegerField()),
                ('id_usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
            ],
        ),
    ]
