# Generated by Django 4.1.3 on 2023-01-11 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cobros',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=30),
        ),
    ]
