# Generated by Django 4.1.3 on 2022-11-29 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=30)),
                ('apellidos', models.CharField(max_length=30)),
                ('celular', models.CharField(max_length=10)),
                ('cedula', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('deuda', models.CharField(choices=[('s', 'si'), ('n', 'no')], default='n', max_length=1)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'clientes',
                'db_table': 'cliente',
                'ordering': ['id'],
            },
        ),
    ]
