# Generated by Django 4.1.3 on 2022-11-30 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='direccion',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
