# Generated by Django 4.1.3 on 2022-11-30 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0006_cliente_detalle_alter_cliente_deuda_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='celular',
            new_name='medidor',
        ),
    ]
