# Generated by Django 4.1.3 on 2022-12-09 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0010_alter_cliente_apellidos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'verbose_name': 'Cliente', 'verbose_name_plural': 'clientes'},
        ),
    ]
