# Generated by Django 4.1.3 on 2022-12-09 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0011_alter_cliente_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={},
        ),
        migrations.AlterModelTable(
            name='cliente',
            table=None,
        ),
    ]
