# Generated by Django 4.1.3 on 2022-12-09 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0012_alter_cliente_options_alter_cliente_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'verbose_name': 'Cliente', 'verbose_name_plural': 'clientes'},
        ),
        migrations.AlterModelTable(
            name='cliente',
            table='cliente',
        ),
    ]
