# Generated by Django 4.1.3 on 2022-12-11 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0013_alter_cliente_options_alter_cliente_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='ultima_cifra',
            field=models.CharField(default='null', max_length=30),
        ),
    ]
