# Generated by Django 4.1.3 on 2022-12-11 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0014_cliente_ultima_cifra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='ultima_cifra',
            field=models.CharField(blank=True, default='null', max_length=30, null=True),
        ),
    ]
