# Generated by Django 4.1.3 on 2022-12-12 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0015_alter_cliente_ultima_cifra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='detalle',
            field=models.CharField(default='-', max_length=30),
        ),
    ]
