# Generated by Django 4.1.3 on 2022-12-07 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0009_alter_cliente_medidor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cifras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.CharField(max_length=10)),
                ('anio', models.CharField(max_length=4)),
                ('cifra', models.IntegerField(max_length=10)),
                ('valor_cifra', models.IntegerField(max_length=5)),
                ('base', models.IntegerField(max_length=5)),
                ('porcentaje_mora', models.IntegerField(max_length=5)),
                ('estado', models.CharField(choices=[('s', 'si'), ('n', 'no')], default='s', max_length=1)),
                ('id_usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
            ],
            options={
                'verbose_name': 'Cifra',
                'verbose_name_plural': 'cifras',
                'db_table': 'cifra',
                'ordering': ['id'],
            },
        ),
    ]
