# Generated by Django 4.1.3 on 2022-12-08 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cifras', '0002_cifras_valor_adicional_alter_cifras_valor_cifra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cifras',
            name='base',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cifras',
            name='cifra',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cifras',
            name='porcentaje_mora',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cifras',
            name='valor_adicional',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='cifras',
            name='valor_cifra',
            field=models.DecimalField(decimal_places=2, max_digits=30),
        ),
    ]
