# Generated by Django 4.1.3 on 2022-12-08 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cifras', '0003_alter_cifras_base_alter_cifras_cifra_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cifras',
            old_name='base',
            new_name='id_valores',
        ),
        migrations.RemoveField(
            model_name='cifras',
            name='porcentaje_mora',
        ),
        migrations.RemoveField(
            model_name='cifras',
            name='valor_adicional',
        ),
        migrations.RemoveField(
            model_name='cifras',
            name='valor_cifra',
        ),
    ]
