# Generated by Django 4.1.3 on 2022-12-09 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cifras', '0004_rename_base_cifras_id_valores_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cifras',
            name='id_valores',
            field=models.CharField(max_length=10),
        ),
    ]
